@HostAddress = http://localhost:5228

GET {{HostAddress}}/api/ping/
Accept: application/json

###

GET {{HostAddress}}/api/vault
Accept: application/json

###

GET {{HostAddress}}/api/vault/1
Accept: application/json

###

POST {{HostAddress}}/api/vault
Content-Type: application/json

{
    "Name": "Mike"
}

###

PUT {{HostAddress}}/api/vault/1
Content-Type: application/json

{
  "Name": "Peter"
}

###

DELETE {{HostAddress}}/api/vault/1
Accept: application/json